Fix: iptables stats tests for iptables >= 1.8.9
coreos/go-iptables pull request #113
Opened 2023-10-16 22:29 UTC by costasd

IPTables fixed a couple long-standing discrepancies in ipv4/ipv6's -L output.
Unfortunately these fixes break out tests and potentially, stat parsing.
    
In detail, the following were changed in 1.8.9 and later:
* ip6tables' opt column not outputting spaces instead of dashes
* ip6tables' prot column not resolving "all" to "0", even with numeric mode activated.
    
 Handle them, so that tests keep working post 1.8.9.

2023-10-23 11:33 UTC, squeed approved these changes

2023-10-23 12:30 UTC, squeed requested changes
@costasd Thanks for your change! It looks like the tests are failing - can you please take a look?

2023-10-23 20:25 UTC, costasd commented
> @costasd Thanks for your change! It looks like the tests are failing - can you please take a look?

Ouch, sorry about that, missed the conditional for IPv4. Added, should work now. Thanks!

2023-11-02 14:16 UTC, squeed approved these changes

2023-11-02 14:17 UTC, merged